---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cabourotte
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cabourotte-discovery
rules:
  - apiGroups:
      - cabourotte.mcorbin.fr
    resources:
      - healthchecks
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cabourotte.mcorbin.fr
    resources:
      - healthchecks/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cabourotte-discovery
subjects:
  - kind: ServiceAccount
    name: cabourotte
    namespace: default
roleRef:
  kind: ClusterRole
  name: cabourotte-discovery
  apiGroup: rbac.authorization.k8s.io

