---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cabourotte
  namespace: default
data:
  cabourotte.yaml: |
    http:
      host: "0.0.0.0"
      port: 9013
    discovery:
      kubernetes:
        service:
          enabled: true
        pods:
          enabled: true
        crd:
          enabled: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cabourotte
  namespace: default
  labels:
    app.kubernetes.io/name: cabourotte
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cabourotte
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cabourotte
    spec:
      serviceAccountName: cabourotte
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - cabourotte
            topologyKey: kubernetes.io/hostname
      containers:
      - name: cabourotte
        image: mcorbin/cabourotte:v0.11.0
        imagePullPolicy: IfNotPresent
        args:
          - daemon
          - --config
          - /config/cabourotte.yaml
        resources:
          limits:
            cpu: 100m
            memory: 80Mi
          requests:
            cpu: 50m
            memory: 40Mi
        ports:
        - containerPort: 9013
          name: api
          protocol: TCP
        securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1664
        livenessProbe:
          httpGet:
            path: /healthz
            port: api
            scheme: HTTP
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: api
            scheme: HTTP
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        startupProbe:
          httpGet:
            path: /healthz
            port: api
            scheme: HTTP
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 20
        volumeMounts:
        - name: cabourotte
          mountPath: /config
          readOnly: true
      volumes:
      - name: cabourotte
        configMap:
          name: cabourotte
